#ifndef SFML_INCLUDES
#define SFML_INCLUDES
#endif
//This file contains the texture coordinates for the sprites in the texture sheet

//      ---    SINGLE TEXTURES   ---    //
const sf::Vector2i DOT_TEXTURE(TILE_SIZE * 13 -4, +2);
const sf::Vector2i SUPERDOT_TEXTURE(TILE_SIZE * 14 -4, + 2);
const sf::Vector2i ORB_TEXTURE(TILE_SIZE * 9 -10, +2);

//   ---  FRUITS   ---    //
const sf::Vector2i CHERRY_TEXTURE(TILE_SIZE * 13-6, TILE_SIZE * 2+4); 
const sf::Vector2i BANANA_TEXTURE(TILE_SIZE * 14-4, TILE_SIZE * 2+4);
const sf::Vector2i APPLE_TEXTURE(TILE_SIZE * 7 + 9, TILE_SIZE*8+ 11);
const sf::Vector2i PINEAPPLE_TEXTURE(TILE_SIZE * 13-6, TILE_SIZE*6+ 8);
const sf::Vector2i YELLOW_KEY_TEXTURE(TILE_SIZE * 17 - 2, + 2);
const sf::Vector2i RED_POTION_TEXTURE(TILE_SIZE * 16 - 3, TILE_SIZE*4+ 7);

//    ---  CHASING GHOSTS   ---    //
const sf::Vector2i RED_GHOST_TEXTURE_LEFT(TILE_SIZE * 9-9, TILE_SIZE * 2+5);
const sf::Vector2i RED_GHOST_TEXTURE_RIGHT(TILE_SIZE * 10-9, TILE_SIZE * 2+5); 
const sf::Vector2i RED_GHOST_TEXTURE_DOWN(TILE_SIZE * 11-7, TILE_SIZE * 2+5); 
const sf::Vector2i RED_GHOST_TEXTURE_UP(TILE_SIZE * 12-7, TILE_SIZE * 2+5);

const sf::Vector2i PINK_GHOST_TEXTURE_LEFT(TILE_SIZE * 5 - 13, TILE_SIZE +4);
const sf::Vector2i PINK_GHOST_TEXTURE_RIGHT(TILE_SIZE * 6 - 13, TILE_SIZE +4);
const sf::Vector2i PINK_GHOST_TEXTURE_DOWN(TILE_SIZE * 7 - 11, TILE_SIZE +4);
const sf::Vector2i PINK_GHOST_TEXTURE_UP(TILE_SIZE * 8 - 11, TILE_SIZE +4);

const sf::Vector2i GREEN_GHOST_TEXTURE_LEFT(3, TILE_SIZE * 2+5); 
const sf::Vector2i GREEN_GHOST_TEXTURE_RIGHT(TILE_SIZE + 3, TILE_SIZE * 2+5); 
const sf::Vector2i GREEN_GHOST_TEXTURE_DOWN(TILE_SIZE * 2+5, TILE_SIZE * 2+5); 
const sf::Vector2i GREEN_GHOST_TEXTURE_UP(TILE_SIZE * 3+5, TILE_SIZE * 2+5); 

const sf::Vector2i ORANGE_GHOST_TEXTURE_LEFT(TILE_SIZE * 5-13, TILE_SIZE * 2+5);
const sf::Vector2i ORANGE_GHOST_TEXTURE_RIGHT(TILE_SIZE * 6-13, TILE_SIZE * 2+5);
const sf::Vector2i ORANGE_GHOST_TEXTURE_DOWN(TILE_SIZE * 7-11, TILE_SIZE * 2+5);
const sf::Vector2i ORANGE_GHOST_TEXTURE_UP(TILE_SIZE * 8-11, TILE_SIZE * 2+5);

//   ---  FRIGHTENED GHOSTS   ---    //
const sf::Vector2i FRIGHTENED_GHOST_TEXTURE_LEFT(3,TILE_SIZE +4);
const sf::Vector2i FRIGHTENED_GHOST_TEXTURE_RIGHT(TILE_SIZE + 3,TILE_SIZE +4);
const sf::Vector2i FRIGHTENED_GHOST_TEXTURE_DOWN(TILE_SIZE * 2 + 5,TILE_SIZE +4); 
const sf::Vector2i FRIGHTENED_GHOST_TEXTURE_UP(TILE_SIZE * 3 + 5,TILE_SIZE +4);

//   ---  PACMAN   ---    //
const int PACMAN_ANIMATION_SPEED = 150; //In milliseconds
const int PACMAN_FRAMES = 4; //Number of frames in the animation

const sf::Vector2i PACMAN_TEXTURE_RIGHT1(TILE_SIZE * 7 + 8, TILE_SIZE*4+ 7);
const sf::Vector2i PACMAN_TEXTURE_RIGHT2(TILE_SIZE * 6 + 7, TILE_SIZE*4+ 7); 
const sf::Vector2i PACMAN_TEXTURE_RIGHT3(TILE_SIZE * 5 + 7, TILE_SIZE*4+ 7);
const sf::Vector2i PACMAN_TEXTURE_RIGHT4(TILE_SIZE * 4 + 6, TILE_SIZE*4+ 7);
const std::vector<sf::Vector2i> PACMAN_TEXTURE_RIGHT = {PACMAN_TEXTURE_RIGHT1, PACMAN_TEXTURE_RIGHT2, PACMAN_TEXTURE_RIGHT3, PACMAN_TEXTURE_RIGHT4};

const sf::Vector2i PACMAN_TEXTURE_LEFT1(TILE_SIZE * 4 + 8, TILE_SIZE*3+ 6);
const sf::Vector2i PACMAN_TEXTURE_LEFT2(TILE_SIZE * 5 + 9, TILE_SIZE*3+ 6);
const sf::Vector2i PACMAN_TEXTURE_LEFT3(TILE_SIZE * 6 + 9, TILE_SIZE*3+ 6);
const sf::Vector2i PACMAN_TEXTURE_LEFT4(TILE_SIZE * 7 + 10, TILE_SIZE*3+ 6);
const std::vector<sf::Vector2i> PACMAN_TEXTURE_LEFT = {PACMAN_TEXTURE_LEFT1, PACMAN_TEXTURE_LEFT2, PACMAN_TEXTURE_LEFT3, PACMAN_TEXTURE_LEFT4};

const sf::Vector2i PACMAN_TEXTURE_DOWN1(TILE_SIZE * 4 + 7, TILE_SIZE*5+ 8);
const sf::Vector2i PACMAN_TEXTURE_DOWN2(TILE_SIZE * 5 + 8, TILE_SIZE*5+ 8);
const sf::Vector2i PACMAN_TEXTURE_DOWN3(TILE_SIZE * 6 + 9, TILE_SIZE*5+ 8);
const sf::Vector2i PACMAN_TEXTURE_DOWN4(TILE_SIZE * 7 + 9, TILE_SIZE*5+ 8);
const std::vector<sf::Vector2i> PACMAN_TEXTURE_DOWN = {PACMAN_TEXTURE_DOWN1, PACMAN_TEXTURE_DOWN2, PACMAN_TEXTURE_DOWN3, PACMAN_TEXTURE_DOWN4};

const sf::Vector2i PACMAN_TEXTURE_UP1(TILE_SIZE * 4 + 7, TILE_SIZE*6+ 9);
const sf::Vector2i PACMAN_TEXTURE_UP2(TILE_SIZE * 5 + 8, TILE_SIZE*6+ 9);
const sf::Vector2i PACMAN_TEXTURE_UP3(TILE_SIZE * 6 + 9, TILE_SIZE*6+ 9);
const sf::Vector2i PACMAN_TEXTURE_UP4(TILE_SIZE * 7 + 9, TILE_SIZE*6+ 9);
const std::vector<sf::Vector2i> PACMAN_TEXTURE_UP = {PACMAN_TEXTURE_UP1, PACMAN_TEXTURE_UP2, PACMAN_TEXTURE_UP3, PACMAN_TEXTURE_UP4};


//   --- SUPER PACMAN   ---    //
const sf::Vector2i SUPER_PACMAN_TEXTURE_RIGHT1(TILE_SIZE * 3 + 4, TILE_SIZE*4+ 7);
const sf::Vector2i SUPER_PACMAN_TEXTURE_RIGHT2(TILE_SIZE * 2 + 3, TILE_SIZE*4+ 7);
const sf::Vector2i SUPER_PACMAN_TEXTURE_RIGHT3(TILE_SIZE * 1 + 3, TILE_SIZE*4+ 7);
const sf::Vector2i SUPER_PACMAN_TEXTURE_RIGHT4(TILE_SIZE * 0 + 2, TILE_SIZE*4+ 7);
const std::vector<sf::Vector2i> SUPER_PACMAN_TEXTURE_RIGHT = {SUPER_PACMAN_TEXTURE_RIGHT1, SUPER_PACMAN_TEXTURE_RIGHT2, SUPER_PACMAN_TEXTURE_RIGHT3, SUPER_PACMAN_TEXTURE_RIGHT4};

const sf::Vector2i SUPER_PACMAN_TEXTURE_LEFT1(TILE_SIZE * 0 + 4, TILE_SIZE*3+ 6);
const sf::Vector2i SUPER_PACMAN_TEXTURE_LEFT2(TILE_SIZE * 1 + 5, TILE_SIZE*3+ 6);
const sf::Vector2i SUPER_PACMAN_TEXTURE_LEFT3(TILE_SIZE * 2 + 5, TILE_SIZE*3+ 6);
const sf::Vector2i SUPER_PACMAN_TEXTURE_LEFT4(TILE_SIZE * 3 + 6, TILE_SIZE*3+ 6);
const std::vector<sf::Vector2i> SUPER_PACMAN_TEXTURE_LEFT = {SUPER_PACMAN_TEXTURE_LEFT1, SUPER_PACMAN_TEXTURE_LEFT2, SUPER_PACMAN_TEXTURE_LEFT3, SUPER_PACMAN_TEXTURE_LEFT4};

const sf::Vector2i SUPER_PACMAN_TEXTURE_DOWN1(TILE_SIZE * 0 + 3, TILE_SIZE*5+ 8);
const sf::Vector2i SUPER_PACMAN_TEXTURE_DOWN2(TILE_SIZE * 1 + 4, TILE_SIZE*5+ 8);
const sf::Vector2i SUPER_PACMAN_TEXTURE_DOWN3(TILE_SIZE * 2 + 5, TILE_SIZE*5+ 8);
const sf::Vector2i SUPER_PACMAN_TEXTURE_DOWN4(TILE_SIZE * 3 + 5, TILE_SIZE*5+ 8);
const std::vector<sf::Vector2i> SUPER_PACMAN_TEXTURE_DOWN = {SUPER_PACMAN_TEXTURE_DOWN1, SUPER_PACMAN_TEXTURE_DOWN2, SUPER_PACMAN_TEXTURE_DOWN3, SUPER_PACMAN_TEXTURE_DOWN4};

const sf::Vector2i SUPER_PACMAN_TEXTURE_UP1(TILE_SIZE * 0 + 3, TILE_SIZE*6+ 9);
const sf::Vector2i SUPER_PACMAN_TEXTURE_UP2(TILE_SIZE * 1 + 4, TILE_SIZE*6+ 9);
const sf::Vector2i SUPER_PACMAN_TEXTURE_UP3(TILE_SIZE * 2 + 5, TILE_SIZE*6+ 9);
const sf::Vector2i SUPER_PACMAN_TEXTURE_UP4(TILE_SIZE * 3 + 5, TILE_SIZE*6+ 9);
const std::vector<sf::Vector2i> SUPER_PACMAN_TEXTURE_UP = {SUPER_PACMAN_TEXTURE_UP1, SUPER_PACMAN_TEXTURE_UP2, SUPER_PACMAN_TEXTURE_UP3, SUPER_PACMAN_TEXTURE_UP4};